apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-ipvlanl2
spec:
  subnet: "192.168.0.0/16"
  ipam: |
    { "type": "whereabouts" }
  multiNICIPAM: false
  plugin:
    cniVersion: "0.3.0"
    type: ipvlan
    args: 
      mode: l2
