# This workflow will be run manually on demand
# to generate catalog image with specific set of bundles with specific tag for testing purpose.
# To trigger this workflow,
# please check https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow.
name: Build Developing Operator Catalog

on:
  workflow_dispatch:
    inputs:
      bundle_images:
        description: 'comma-separated list of bundle images'
        required: true
      tag:
        description: 'image tag'
        required: true



jobs:
  build-catalog:
    runs-on: ubuntu-latest

    env:
      CATALOG_IMG: ghcr.io/${{ github.repository }}-catalog:${{ github.event.inputs.tag }}
      BUNDLE_IMGS: ${{ github.event.inputs.bundle_images }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Operator Catalog
        run: |
          make catalog-build catalog-push
